apiVersion: v1
kind: Service
metadata:
  name: elixir-drip-loadbalancer
  namespace: production
  labels:
    app: elixir-drip
    env: production
spec:
  type: LoadBalancer
  selector:
    app: elixir-drip
    env: production
  ports:
    - port: 80
      targetPort: 4000
