apiVersion: v1
kind: Service
metadata:
  name: elixir-drip-loadbalancer
  namespace: production
  labels:
    app: elixir-drip
    env: production
spec:
  type: LoadBalancer
  selector:
    app: elixir-drip
    env: production
  ports:
    - name: web
      port: 80
      targetPort: 4000
    - name: epmd
      port: 4369
      targetPort: 4369
    - name: inet-dist-listen
      port: 9001
      targetPort: 9001
